name: "🚀 publish"

on:
  release:
    types: [created]

jobs:
  publish-npm:
    name: 🚀 publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: ☄️ checkout
        uses: actions/checkout@v2

      - name: 🐱‍🏍 node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registery-url: https://registry.npmjs.org/

      - name: 📦 install dependencies
        run: yarn install --frozen-lockfile

      - name: ☄️ build
        run: yarn build

      - name: 🚀 publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
